ego_state_topic_name: /ego_state
rline_topic_name: /rline
obstacles_topic_name: /obstacles

trajectory_topic_name: /trajectory/dp_line

node_rate: 10

viz: true
viz_trajectory_topic_name: /viz/trajectory/dp_line

#path_planning dp
w_cost_collision: 999999
w_cost_smooth_dl: 300
w_cost_smooth_ddl: 2000
w_cost_smooth_dddl: 10000
w_cost_ref: 20
row: 9
col: 6
sample_s: 10
smaple_l: 1

#path_planning qp
w_cost_l: 5
w_cost_dl: 50000
w_cost_ddl: 300
w_cost_dddl: 15
w_cost_centre: 1200
w_cost_end_l: 40
w_cost_end_dl: 40
w_cost_end_ddl: 40

#velocity_planning
recommend_velocity: 15

#velocity_planning dp
w_cost_ref_speed: 400
w_cost_accel: 100
w_cost_obs: 99999

#velocity_planning qp
w_cost_s_dot2: 10
w_cost_v_ref: 50
w_cost_jerk: 500